/****** Object:  Table [ORTAK].[FOTOGRAF]    Script Date: 05/15/2007 00:44:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ORTAK].[FOTOGRAF](
	[ID] [uniqueidentifier] NOT NULL,
	[KisiKey] [uniqueidentifier] NOT NULL,
	[FotografVerisi] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_FOTOGRAF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

