/****** Object:  Table [ORTAK].[KISI_ADRES]    Script Date: 05/15/2007 00:44:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ORTAK].[KISI_ADRES](
	[ID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_KISI_ADRES_ID]  DEFAULT (newid()),
	[KisiKey] [uniqueidentifier] NOT NULL,
	[Adres] [ORTAK].[Adres] NULL,
	[AdresTuruTipNo] [tinyint] NULL,
	[Oncelik] [int] NULL,
	[AktifMi] [bit] NULL CONSTRAINT [DF_Adres_Durum]  DEFAULT ((1)),
 CONSTRAINT [PK_KISI_ADRES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

