ALTER TABLE [ORTAK].[KISI_ILETISIM]  WITH CHECK ADD  CONSTRAINT [FK_KISI_ILETISIM_ILETISIM_TURU] FOREIGN KEY([IletisimTuruTipNo])
REFERENCES [ILETISIM_TURU] ([No])
GO
ALTER TABLE [ORTAK].[KISI_ILETISIM] CHECK CONSTRAINT [FK_KISI_ILETISIM_ILETISIM_TURU]
GO
ALTER TABLE [ORTAK].[KISI_ILETISIM]  WITH CHECK ADD  CONSTRAINT [FK_KISI_ILETISIM_KISI] FOREIGN KEY([KisiKey])
REFERENCES [KISI] ([ID])
GO
ALTER TABLE [ORTAK].[KISI_ILETISIM] CHECK CONSTRAINT [FK_KISI_ILETISIM_KISI]
GO

