ALTER TABLE [ORTAK].[KISI_ADRES]  WITH CHECK ADD  CONSTRAINT [FK_KISI_ADRES_ADRES_TURU] FOREIGN KEY([AdresTuruTipNo])
REFERENCES [ADRES_TURU] ([No])
GO
ALTER TABLE [ORTAK].[KISI_ADRES] CHECK CONSTRAINT [FK_KISI_ADRES_ADRES_TURU]
GO
ALTER TABLE [ORTAK].[KISI_ADRES]  WITH CHECK ADD  CONSTRAINT [FK_KISI_ADRES_KISI] FOREIGN KEY([KisiKey])
REFERENCES [KISI] ([ID])
GO
ALTER TABLE [ORTAK].[KISI_ADRES] CHECK CONSTRAINT [FK_KISI_ADRES_KISI]
GO

