using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace Karkas.MyGenerationHelper
{
    public class TurkishHelper
    {
        Dictionary<string, string> liste = new Dictionary<string, string>();
        public TurkishHelper()
        {
            liste.Add("Adi", "Adý");
            liste.Add("Tur", "Tür");
            liste.Add("Kisi", "Kiþi");
            liste.Add("Ogrenim", "Öðrenim");
            liste.Add("Bolum", "Bolüm");
            liste.Add("Giris", "Giriþ");
            string a = @"
            Aciklama
Ad
AdaNo
Adet
Adi
Adres
AdresKey
AdresTuruTipNo
AhzukapsYetkiBaslangicTarihi
AhzukapsYetkisiliMi
AktifMi
AkzukapsYetkiSuresi
Alan1
Alan2
AmacVeKonu
AmacVeKonuTipNo
AmacVeKonuTuruTipNo
AnaAdi
AnaRehinKey
AnaSozlesmeMaddeNo
AracVarmi
ArttirmaYapilmasiGerekenSonTarih
ÅžubelerdeRehinVarmi
AyniSermayeAciklama
AyniSermayeHisseAdeti
AyniSermayeMiktari
BabaAdi
BagliOlduguBankaTipNo
BagliOlduguMakbuzNo
BagliOlduguTSMTipNo
BagliOlduguVakifDernekAdi
BakanlikIzinTarihi
BakanlikIzinYazisiEvrakKey1
BankaAdi
BankaNo
BankaParentKey
BankaTipNo
BankoMemurununGirdigiAdet
BasimSayi
BasimTarihi
BaslamaTarihi
BaslangicTarih
BaslangicTarihi
BasTarih
BasvuruDurumNo
BasvuruYapanKisiAdSoyad
BasvuruYapanKisiTCKimlikNo
BasvuruYapanKisiTelefonNo
BasvuruYapilanSubeKey
Beklenti
BeklentiAciklama
BelediyeAdi
BelgeAciklama
BelgeAdi
BelgeDegiskenAlan1
BelgeDegiskenAlan2
BelgeDegiskenAlan3
BelgeDegiskenAlan4
BelgeDegiskenAlan5
BelgeDurumTipNo
BelgeEvrakKey
BelgeIadeAlanKullanciKey
BelgeIadeEvrakKey
BelgeIadeTarihi
BelgeninGonderilmeTuruTipNo
BelgeninTeslimEdildigiTarih
BelgeninTeslimEdilecegiTarih
BelgeNumarasi
BelgeOlusturmaTarihi
BelgeTalepAmaciAciklama
BelgeTalepKey
BelgeTuruTipNo
BelgeyiOlusturanKullaniciKey
BelgeyiOnaylayanKullaniciKey
BelgeyiTalepEdenKurum
BelgeyiTeslimAlanKisiTCKimlikNo
BildirimDurumAciklama
BildirimEvrakKey
BildirimTarihi
BilgilendirmeEvrakKey
BirHisseDegeri
BitirmeDerecesi
BitisTarih
BitisTarihi
BitTarih
Blok
Bolum
BolumKey
BolunmeyenSermaye
Bucak
Bulvar
Cadde
CalismaDurumu
CezaOdemeMakbuzNo
CikarilmisSermaye
CikarilmisSermayeBaslangicTarihi
CikarilmisSermayeBitisTarihi
CikisTarih
Cilt
CinsiyetTuruTipNo
CV
DavaTarihi
DefterTastigiVarMi
DenetciKey
DenetimKuruluKey
Derece
DereceTipNo
Diger
DinTuruTipNo
DisKapiNo
DogumTarihi
DogumYeriNo
Durum
DurumCikisTarihi
DurumGirisTarihi
DurumKisaAciklama
DurumNo
DurumTipi
DurumTipNo
DurumUzunAciklama
EgitimTurNo
EgitimYer
EhliyetKey
EkIsyeriAdeti
EserAd
EskiHali
EvrakBilirKisiAtamaMahkemeKarariKey
EvrakBilirKisiRaporuKey
EvrakIadeKararlariKey
EvrakKey
EvraklarinPostayaVerilmeTarihi
EvraklarinTeslimTarihi
EvrakTipNo
FaizMiktar
Fakulte
FekNoterAdi
FekNoterTarihi
FekSozlesmeKey
FirmaAdi
FirmaAgirlastiriciNisapKey
FirmaAmacVeKonularKey
FirmaCevapEvrakKey
FirmaCevapTarihi
FirmaDurumKey
FirmaDurumTipNo
FirmaEkIsyeriKey
FirmaEvrakNo
FirmaGerekceDurumNo
FirmaHesapDonemiKey
FirmaImtiyazKey
FirmaIntibakBildirimiKey
FirmaIsletmeAdiKey
FirmaKey
FirmaKisitlamaHavuzuKey
FirmaNakilKey
FirmaNeviTipNo
FirmaNeviTurNo
FirmaOdaKey
FirmaOdenmisSermayeKey
FirmaOrtakKey
FirmaParentKey
FirmaSahibiKisiKey
FirmaSektorKey
FirmaSermaye
FirmaSermayeKey
FirmaSermayeOrtakKey
FirmaSozlesmeKey
FirmaSozlesmeMaddeleriKey
FirmaTuruTipNo
FirmaTuzelOrtakKey
FirmaUnvan
FirmaUnvanKey
FirmayaGonderilenEvrakKey
FirmaYonetimKuruluKey
FizikselEngelli
FotografVerisi
GayrimenkulVarmi
GazeteBaslangicSayfaNo
GazeteBitisSayfaNo
GazeteNo
GazeteSayisi
GazeteTarihi
GecerlilikSirasi
GenelKurulUyeTipNo
GerekceRedSebep
GeriDonusTarihi
GeriOdemeAciklama
GeriOdemeBasvurusuEvrakKey
GeriOdemeKey
GeriOdemeninYapildigiMakbuzNo
GeriOdemeSebebiTipNo
GeriOdemeTarihi
GeriOdemeTuruTipNo
GeriOdenecekMiktar
GirisSene
GirisTarih
GizlilikDerecesiTipNo
GonderenKullaniciKey
GondermeTarihi
GorevBitisTarihi
GorevSuresi
GorevTipNo
HalkaAcikMi
HarcBelirlenmeTarihi
HarcMiktari
HarcTuruNo
HarcTuruTanim
HarcTuruTipNo
HerkesGorebilir
HesapDonemiBaslangicAy
HesapDonemiBaslangicGun
HesapDonemiBitisAy
HesapDonemiBitisGun
HisseAdeti
HisseGrubu
Hobi
IadeBilgisi
IadeBilgisiKey
IadeEdenKullaniciKey
IadeEdilenEvrakIcinAciklama
IadeEdilenEvraklarKey
IadeKarariAlanKullaniciKey
IadeKisiAd
IadeKisiCepTelefonu
IadeKisiIsTelefonu
IadeKisiSoyad
IadeKisiTcKimlikNo
IadeSebebi
IadeTuru
IadeTuruTanim
IadeTuruTipNo
IcKapiNo
ID
IhrazatciMi
IhtarDurumNo
IhtarGonderilenEvrakKey
IhtariKaldiranKullaniciKey
IhtariOnaylayanKullaniciKey
IhtariSistemeGirenKullaniciKey
IhtarKey
IhtarMahkemeKey
IhtarOlusturmaTarihi
IhtarSebebi
IhtarSebebiEkBilgi
IhtarSonucundaYapilanIslemlerKey
IhtarSure
IhtarTarihi
IkinciAdi
IkmalBildirimEvrakKey
IkmalKey
IkmalMakbuzuNo
IkmalMiktari
IkmalOdemeTuruTipNo
IkmalSebebi
IkmalTarihi
IlanAciklama
IlanBasvuruEvrakKey
IlaniGonderenSubeTipNo
IlanKelimeAdeti
IlanKey
IlanMetni
IlanTuruAciklama
IlanTuruTipNo
IlceKey
IlceNo
IlceTipNo
Iletisim
IletisimKey
IletisimNumarasi
IletisimTuruTipNo
IlkGecerlilikTarihi
IlTipNo
ImtiyazGrubuTipNo
ImtiyazNotu
ImtiyazVarMi
IngilizceAdi
IntiyazGrubu
IsAdresiTuruMu
IsaretVarmi
IseBaslamaTarihi
IslemAciklamasi
IslemAdi
IslemiSistemeGirenKullaniciKey
IslemiSonuclandiranSubeTipNo
IslemiYapanKullaniciKey
IslemlerKey
IslemOnaylayanKullaniciKey
IslemSekilleriTipNo
IslemSekli
IslemSekliNo
IslemTuruTipNo
IslemYapanSubeTipNo
IsletmeAdi
IsStandard
IstanbulDisiUyeAdres
IstanbulDisiUyeMemurlukAdi
IstanbulDisiUyemi
IstanbulDisiUyeSicilNo
IstanbulDisiUyeUnvan
IsTanimi
IstenilenGazeteAdeti
IstenilenMeslekGrubuTipNo
IstihbarataGonderenKullaniciKey
IstihbarataGonderilenEvrakSevkNo
IstihbaratKisitlamaKey
IstihbaratRaporuKey
IstihbaratTalebiKey
IstihbaratTalebiOnaylayanSefKey
IstihbaratTalepEden
IstihbaratTalepEdeneGonderilmeTarihi
IstihbaratTalepEdenIcSubeTipNo
IstihbaratTalepTarihi
IstihbarattanGelisTarihi
IstihbaratYapacakOlanMemurKey
IstihbaratYapanMemurKey
ITOEvrakKey
ITOPersoneliGorebilir
ItoUyesimi
KaldirilmaTarihi
KaldirmayiOnaylayanAmirKey
KamusalMi
KanGrubuTipNo
KapanisTarihi
KapanisTuruTipNo
KaraListeCikisKararlarKey
KaraListeCikisTarihi
KaraListeGirisKararlarKey
KaraListeGirisTarihi
KaraListeKey
Karar
KararEvrakKey
KararlarGenelKurulYillariKey
KararlarKey
KararNo
KararTarih
KararTarihi
KararTuruTipNo
Kategori
KategoriTipNo
KayitEdenHizmetBirimiTipNo
KayitliSermaye
KayitTarihi
KelimeAdeti
KisaAd
KisaAdi
KisiKey
KisiSayisi
KisitlamaIcerigi
KisitlamaninEngelledigiIslemlerKey
KisitlamaninGeldigiKararlarKey
KisitlamaTuruTipNo
KisitlamaVarMi
KisitlamayiGirenMemurKey
KisitlamayiKaldiraniKararlarKey
KisitlamayiKaldiranMemurKey
KisitlamayiOnaylayanAmirKey
KismiFekKey
Kodu
KomanditMi
Konu
KooperatifTip
KooperatifTipNo
KooperatifTuruTipNo
Koy
Kriter
KullaniciKey
KurucuMu
KurucuVekilBilgisiKey
KurumKey
Kutuk
ListeDurumNo
ListeTarihi
LogKey
MaddeAdi
MaddeIcerik
Mahalle
MahkemeAdi
MahkemeDosyaNo
MahkemeDosyaYili
MahkemeKararEvrakKey
MahkemeKarariEkBilgi
MahkemeKararTipNo
MahkemeNumarasi
MakbuzNo
MakbuzTarihi
MaksimumSayi
MaksimumSure
MedeniDurumTuruTipNo
Memnun
MemnunAciklama
MemurAciklama
MemurGorebilir
MemurGorevTipi
MesajInternet
MesajITO
MesajOlarakGorunecekMi
MeslekGrubuAmacVeKonularKey
MeslekGrubuDegisikligiListeKey
MeslekGrubuDegisiklikBasvurusuKey
MeslekGrubunaGonderilenAmacVeKonu
MeslekGrubuTipNo
MeslekGruplariTipNo
MeslekKomitesiKararAciklama
MeslekKomitesiKey
MeslekKomitesindenGelenEvrakKey
MeslekKomitesindenGelisTarihi
MeslekKomitesineGonderilmeEvrakKey
MeslekKomitesineGonderilmeTarihi
MevkiAdi
Mezra
MezuniyetNotu
MezuniyetSene
MinimumSayi
MinimumSure
MTKNo
MudurOnayTarihi
MunferitMi
MunferitTemsilSinirlari
MusterekMi
MusterekTemsilSinirlari
NakdiSermayeHisseAdeti
NakdiSermayeMiktari
NakilTuruTipNo
NeviTuruNo
NisapNot
No
NoterAdi
NoterTarih
NoterTarihi
NoterYevmiyeNo
NufusaKayitliOlduguIlceNo
NufusaKayitliOlduguMahalleKoyKey
NufusaKayitliOlduguSehirNo
OdaGazeteKey
OdaGazetesiAbonesiOlacakMi
OdaKayitÄ°ptalTarihi
OdaKayitTarihi
OdaTipNo
OdaUyeligiZorunluMu
OdaUyesiMi
OdaUyesiOlacakMi
OdemeDurumTanim
OdemeDurumTipNo
OdemeTuruTanim
OdemeTuruTipNo
OdenmesiGerekenMiktar
OdenmeTarihi
OdenmisMiktar
OgrendigiYerKey
OgrenimTipKey
OgrenimTipNo
OkulAd
OkulKey
OkumaDerecesi
OlmasiGerekenSermayeYasalMiktari
OnaylayanKullaniciKey
Oncelik
OrtaklikTipNo
OzSermaye
PaftaNo
ParaCezasiMiktar
ParselNo
PasaportKey
PasaportNo
PasaportTipNo
PatentVarmi
PlakaKod
PostaKodu
PostalandigiTarih
PostaNo
RaporEvrakKey
RaporSonucuAciklama
RaporTarihi
ReddedilmeSebebi
ReddedilmeTarihi
RedKarariAlanKullaniciKey
RedKararlariKey
RedTurleri
RedTuruTipNo
ReferansAdi
ReferansEmail
ReferansFirmasi
ReferansIkinciAdi
ReferansPozisyonKey
ReferansSoyadi
ReferansTelefon
ReferansUnvanKey
RehinAlacaklilarKey
RehinDetayKey
RehinKey
RehinMiktar
RehinNumarasi
RehinSozlemeKey
RehinSozlesmeKey
RehinSozlesmeTip
RekabetKuruluPayiYatirilacakMi
RekabetPayiYatirilabilirMi
RekKurulPayKey
SaglikEngelli
Sayfa
Sebep
SecilmeSuresi
SecilmeTarihi
SecimMeslekGrubuTipNo
SefOnayTarihi
SehirKey
SehirNo
Sektor
SektorlerTipNo
SektorTipNo
SerbestAdres
Sermaye
SermayeArttirimiYapmayanlaraGonderilenEvrakKey
SermayeYasalSiniriKey
ServisSefiGorebilir
SicilDurumTipNo
SicilNo
SigaraKullanimi
Sigorta
SigortaParasi
Sinif
Sinifi
SistemdenKaldiranKullaniciKey
SistemeGirenKullaniciKey
SistemeGirisTarihi
Site
Sokak
SonGecerlilikTarihi
SonMezuniyetTipNo
SonTamUnvan
SosyalGuvenlikNo
SosyalGuvenlikTipNo
Soyad
Soyadi
SozlesmeDuzenlenmeTarihi
SozlesmeKarar
SozlesmeMaddeTuruTipNo
SozlesmeTarihi
SPKIzinTarihi
SPKIzinYazisiEvrakKey
StajyerKisiKey
SuankiMeslekGrubuTipNo
Sube
SubeAdi
SubeKod
SubeMudurGorebilir
SubeTipNo
SubeTuruTipNo
Suresi
SureSonu
SureYil
TalebiKontrolEdecekSicilMemuruKey
TalebinAlindigiHizmetBirimiTipNo
TalebinGeldigiEvrakKey
TalebiSistemeKaydedenKullaniciKey
TalepAciklama
TalepDurumIstekSahibi
TalepDurumITO
TalepDurumTipNo
TalepEdenAd
TalepEdenCepTelefon
TalepEdenFirmaUnvan
TalepEdenIsTelefonu
TalepEdenKurumAd
TalepEdenSoyad
TalepEdenSubeInceleme
TalepEdenSubeOneri
TalepEdenTcKimlikNo
TalepEdilenAdet
TalepEdilenBelgeTuruTipNo
TalepEdilenFirmaKey
TalepEvrakKey
TalepGelisTarihi
TalepGelisTuruTanim
TalepGelisTuruTipNo
TalepIadeKey
TalepIslemTurleriKey
TalepKararTurleriKey
TalepKey
TalepKurulusKey
TalepMudurOnayTarihi
TalepNo
TalepNotKey
TalepNotu
TalepOdemeKey
TalepSefOnayTarihi
TalepTarihi
TalepTuru
TalepTuruTanim
TalepTuruTipNo
TamUnvan
Tarih
TarihBaslangic
TarihBitis
TCKimlikNo
TebligTarihi
TelefonHatSayisi
TemditTarihi
TemsilcilerKey
TemsilciSayisi
TemsilSekilleriTipNo
TescileTabiMi
TescilMemurlarKey
TescilTarihi
TeslimAlanKisiAdSoyad
TeslimTarihi
TicariSermaye
TipNo
ToplamAyniSermaye
ToplamNakdiSermaye
ToplamSermaye
TSMAdi
TSMEvrakKey
Tur
TurkiyeIcindeMi
TuzelOrtakTemsilciKey
UcretsizIlanaOnayVerenKullaniciKey
UlkeAdi
UlkeKey
UlkeKisaltmasi
UlkeNo
UlkeTipNo
Unvan
Unvani
Uyari
UyelikTuruTipNo
UyeOlduguDernekler
UyrukTipNo
UzunAd
UzunAdi
VakifMi
VekaletNameNo
VekaletnameTarih
VekilAdres
VekilIsmi
VekilKisiKey
VekilYetki
VergiDairesiTipNo
VergiNo
WindowsUserName
YabanciDilTipi
YabanciDilTipNo
YanitlayanKisiKey
YasaEvrakKey
YatirilanMiktar
YatirilanOran
YazmaDerecesi
Yemek
YemekParasi
YeniGelenEvrakKey
YeniHali
YetkiliStajyerSorumlusu
YetkiSuresi
YevmiyeNumarasi
Yil
Yol
YolParasi
YonetimKuruluKey
YonetimKuruluUyeleriKey
YurtDisiUyeAdres
YurtDisiUyemi
YurtDisiUyeUnvan
            ";
                
        }

        public string ReplaceTurkishChars(string str)
        {
            str = str.Replace('ð', 'g');
            str = str.Replace('Ð', 'G');

            str = str.Replace('ü', 'u');
            str = str.Replace('Ü', 'U');

            str = str.Replace('þ', 's');
            str = str.Replace('Þ', 'S');

            str = str.Replace('ý', 'i');
            str = str.Replace('Ý', 'I');

            str = str.Replace('ö', 'o');
            str = str.Replace('Ö', 'O');

            str = str.Replace('ç', 'c');
            str = str.Replace('Ç', 'C');

            return str;
        }




        /// <summary>
        /// Ingilizce harfleri ile yazýlmýþ bir kelimeyi türkçe harflere çevirir.
        /// </summary>
        /// <param name="cevirilecekKelime"></param>
        /// <returns></returns>
        public string TurkceyeCevir(string cevirilecekKelime)
        {
            if (liste.ContainsKey(cevirilecekKelime))
            {
                return liste[cevirilecekKelime];
            }
            else
            {
                foreach (string s in liste.Keys)
                {
                    Regex reg = new Regex(s, RegexOptions.IgnoreCase);
                    Match m = reg.Match(cevirilecekKelime);
                    if (m.Success)
                    {
                        return cevirilecekKelime.Replace(m.Value, liste[s].ToLower());
                    }
                }

                return cevirilecekKelime;
            }

        }
    }
}
